name: Build SURVIVOR-BR
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/sdks/master/install.sh)"
          echo "THEOS=/opt/theos" >> $GITHUB_ENV

      - name: Make executable
        run: chmod +x build.sh

      - name: Compile Tweak
        run: ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Survivor-BR-Package
          path: packages/*.deb
